### ISSUE TITLE
Bug build get_monitors / randr on xubuntu

### ISSUE THREAD

**Issue by ChoiZ** [jaagr/polybar#345]
When I build on xubuntu 16.10:

I follow the instructions:
  $ git clone --branch 2.5.2 --recursive https://github.com/jaagr/polybar
  $ mkdir polybar/build
  $ cd polybar/build
  $ cmake ..
  $ sudo make install

```
[ 81%] Building CXX object bin/CMakeFiles/polybar.dir/x11/extensions/randr.cpp.o
/home/choiz/Repos/polybar/src/x11/extensions/randr.cpp: In function ‘std::vector<std::shared_ptr<polybar::v2_0_0::randr_output> > polybar::v2_0_0::randr_util::get_monitors(polybar::v2_0_0::connection&, xcb_window_t, bool, bool)’:
/home/choiz/Repos/polybar/src/x11/extensions/randr.cpp:89:30: error: ‘class polybar::v2_0_0::connection’ has no member named ‘get_monitors’; did you mean ‘get_controls’?
       for (auto&& mon : conn.get_monitors(root, true).monitors()) {
                              ^~~~~~~~~~~~
bin/CMakeFiles/polybar.dir/build.make:1574 : la recette pour la cible « bin/CMakeFiles/polybar.dir/x11/extensions/randr.cpp.o » a échouée
make[2]: *** [bin/CMakeFiles/polybar.dir/x11/extensions/randr.cpp.o] Erreur 1
CMakeFiles/Makefile2:336 : la recette pour la cible « bin/CMakeFiles/polybar.dir/all » a échouée
make[1]: *** [bin/CMakeFiles/polybar.dir/all] Erreur 2
Makefile:127 : la recette pour la cible « all » a échouée
make: *** [all] Erreur 2
** Failed to build project
```

Any idea?

**Comment by taylorthurlow** [comment]
Looks like you have the same issue as #344.

**Comment by alekcacko** [comment]
Yes, it is the same bug.

**Comment by ChoiZ** [comment]
Sorry, though I did a search before posting but the error being on pastebin ... I had no result.

**Comment by alekcacko** [comment]
Okay, no problem :) I won't put logs on pastebin.

**Comment by jaagr** [comment]
It's not a bug, it's because of the XRandR version doesn't support the monitor concept. See #344 on how to disable the use of it.
