### ISSUE TITLE
2.4.0 ftbfs: error: comparison between signed and unsigned integer expressions

### ISSUE THREAD

**Issue by ckorn** [jaagr/polybar#267]
The new version 2.4.0 fails to build on Ubuntu 16.04.

```
/«PKGBUILDDIR»/src/components/config.cpp:254:12: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
   if (conv < std::numeric_limits<unsigned int>::min()) {
            ^
/«PKGBUILDDIR»/src/components/config.cpp:256:19: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
   } else if (conv > std::numeric_limits<unsigned int>::max()) {
                   ^
cc1plus: all warnings being treated as errors
```

This is the entire build log:
http://zulu309.server4you.de/build/logs/polybar_2.4.0-1~getdeb1-i386-20161222-1810

**Comment by jaagr** [comment]
`2.4.1` has been released that includes this fix
