### ISSUE TITLE
Polybar fails to compile with gcc 7.1.1

### ISSUE THREAD

**Issue by gregf** [jaagr/polybar#584]
Trying to install polybar on archlinux which is now on gcc 7.1.1 and I get the following error.

```
[  4%] Building CXX object bin/CMakeFiles/polybar-msg.dir/ipc.cpp.o
[  5%] Building CXX object bin/CMakeFiles/polybar-msg.dir/utils/file.cpp.o
[  7%] Building CXX object bin/CMakeFiles/polybar-msg.dir/utils/env.cpp.o
In file included from /home/gregf/polybar-git/src/polybar/lib/i3ipcpp/src/ipc-util.cpp:16:0:
/home/gregf/polybar-git/src/polybar/lib/i3ipcpp/include/i3ipc++/ipc-util.hpp:147:57: error: dynamic exception specifications are deprecated in C++11 [-Werror=deprecated]
 std::shared_ptr<buf_t>   i3_recv(const int32_t  sockfd) throw (invalid_header_error, eof_error);
                                                         ^~~~~
In file included from /home/gregf/polybar-git/src/polybar/lib/i3ipcpp/src/ipc-util.cpp:16:0:
/home/gregf/polybar-git/src/polybar/lib/i3ipcpp/include/i3ipc++/ipc-util.hpp:163:131: error: dynamic exception specifications are deprecated in C++11 [-Werror=deprecated]
 std::shared_ptr<buf_t>  i3_msg(const int32_t  sockfd, const ClientMessageType  type, const std::string&  payload = std::string()) throw (invalid_header_error, eof_error);
                                                                                                                                   ^~~~~
/home/gregf/polybar-git/src/polybar/lib/i3ipcpp/src/ipc-util.cpp:118:57: error: dynamic exception specifications are deprecated in C++11 [-Werror=deprecated]
 std::shared_ptr<buf_t>   i3_recv(const int32_t  sockfd) throw (invalid_header_error, eof_error) {
                                                         ^~~~~
/home/gregf/polybar-git/src/polybar/lib/i3ipcpp/src/ipc-util.cpp:162:115: error: dynamic exception specifications are deprecated in C++11 [-Werror=deprecated]
 std::shared_ptr<buf_t>  i3_msg(const int32_t  sockfd, const ClientMessageType  type, const std::string&  payload) throw (invalid_header_error, eof_error) {
                                                                                                                   ^~~~~
In file included from /home/gregf/polybar-git/src/polybar/lib/i3ipcpp/src/ipc.cpp:9:0:
/home/gregf/polybar-git/src/polybar/lib/i3ipcpp/include/i3ipc++/ipc-util.hpp:147:57: error: dynamic exception specifications are deprecated in C++11 [-Werror=deprecated]
 std::shared_ptr<buf_t>   i3_recv(const int32_t  sockfd) throw (invalid_header_error, eof_error);
In file included from /home/gregf/polybar-git/src/polybar/lib/i3ipcpp/src/ipc.cpp:9:0:
/home/gregf/polybar-git/src/polybar/lib/i3ipcpp/include/i3ipc++/ipc-util.hpp:163:131: error: dynamic exception specifications are deprecated in C++11 [-Werror=deprecated]
 std::shared_ptr<buf_t>  i3_msg(const int32_t  sockfd, const ClientMessageType  type, const std::string&  payload = std::string()) throw (invalid_header_error, eof_error);
                                                                                                                                   ^~~~~
list: size, ['red', 'green', 'blue']
list: size, ['red', 'green', 'blue']
cc1plus: all warnings being treated as errors
make[2]: *** [lib/i3ipcpp/CMakeFiles/i3ipc++.dir/build.make:87: lib/i3ipcpp/CMakeFiles/i3ipc++.dir/src/ipc-util.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[  8%] Linking CXX executable polybar-msg
[  8%] Built target polybar-msg
cc1plus: all warnings being treated as errors
make[2]: *** [lib/i3ipcpp/CMakeFiles/i3ipc++.dir/build.make:63: lib/i3ipcpp/CMakeFiles/i3ipc++.dir/src/ipc.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:440: lib/i3ipcpp/CMakeFiles/i3ipc++.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  8%] Built target xpp
make: *** [Makefile:130: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by lluixhi** [comment]
I think this is a duplicate of #572, but you have i3 support enabled.

**Comment by jaagr** [comment]
Closing, as @lluixhi said it's a duplicate of #572.
