### ISSUE TITLE
src/utils/file.cpp:156:72: error: no matching function for call to 'max(long int, int&)'

### ISSUE THREAD

**Issue by ckorn** [jaagr/polybar#290]
Version 2.4.5 fails to build on Ubuntu 16.04
```
/«PKGBUILDDIR»/src/utils/file.cpp: In member function 'virtual int polybar::v2_0_0::fd_streambuf::underflow()':
/«PKGBUILDDIR»/src/utils/file.cpp:156:72: error: no matching function for call to 'max(long int, int&)'
     setg(eback(), eback() + pback, eback() + pback + std::max(0L, bytes));
                                                                        ^
In file included from /usr/include/c++/5/bits/char_traits.h:39:0,
                 from /usr/include/c++/5/ios:40,
                 from /usr/include/c++/5/istream:38,
                 from /usr/include/c++/5/fstream:38,
                 from /«PKGBUILDDIR»/src/utils/file.cpp:4:
/usr/include/c++/5/bits/stl_algobase.h:219:5: note: candidate: template<class _Tp> constexpr const _Tp& std::max(const _Tp&, const _Tp&)
     max(const _Tp& __a, const _Tp& __b)
     ^
/usr/include/c++/5/bits/stl_algobase.h:219:5: note:   template argument deduction/substitution failed:
/«PKGBUILDDIR»/src/utils/file.cpp:156:72: note:   deduced conflicting types for parameter 'const _Tp' ('long int' and 'int')
     setg(eback(), eback() + pback, eback() + pback + std::max(0L, bytes));
                                                                        ^
In file included from /usr/include/c++/5/bits/char_traits.h:39:0,
                 from /usr/include/c++/5/ios:40,
                 from /usr/include/c++/5/istream:38,
                 from /usr/include/c++/5/fstream:38,
                 from /«PKGBUILDDIR»/src/utils/file.cpp:4:
/usr/include/c++/5/bits/stl_algobase.h:265:5: note: candidate: template<class _Tp, class _Compare> constexpr const _Tp& std::max(const _Tp&, const _Tp&, _Compare)
     max(const _Tp& __a, const _Tp& __b, _Compare __comp)
     ^
/usr/include/c++/5/bits/stl_algobase.h:265:5: note:   template argument deduction/substitution failed:
/«PKGBUILDDIR»/src/utils/file.cpp:156:72: note:   deduced conflicting types for parameter 'const _Tp' ('long int' and 'int')
     setg(eback(), eback() + pback, eback() + pback + std::max(0L, bytes));
                                                                        ^
make[3]: *** [bin/CMakeFiles/polybar.dir/utils/file.cpp.o] Error 1
```

This is the build log:
http://zulu309.server4you.de/build/logs/polybar_2.4.5-1~getdeb1-i386-20161231-1712

**Comment by jaagr** [comment]
Apply this patch (`git-apply <file>`)
~~~patch
diff --git a/include/utils/file.hpp b/include/utils/file.hpp
index f39f199..0025d69 100644
--- a/include/utils/file.hpp
+++ b/include/utils/file.hpp
@@ -45,7 +45,7 @@ class file_descriptor {
  private:
   int m_fd{-1};
 };
-
+#if 0
 class fd_streambuf : public std::streambuf {
  public:
   using traits_type = std::streambuf::traits_type;
@@ -90,7 +90,7 @@ class fd_stream : public StreamType {
  protected:
   fd_streambuf m_buf;
 };
-
+#endif
 namespace file_util {
   bool exists(const string& filename);
   string pick(const vector<string>& filenames);
diff --git a/src/utils/file.cpp b/src/utils/file.cpp
index c0cb9f6..00d1733 100644
--- a/src/utils/file.cpp
+++ b/src/utils/file.cpp
@@ -95,7 +95,7 @@ void file_descriptor::close() {
 
 // }}}
 // implementation of file_streambuf {{{
-
+#if 0
 fd_streambuf::fd_streambuf(int fd) : m_fd(-1) {
   open(fd);
 }
@@ -157,7 +157,7 @@ int fd_streambuf::underflow() {
   }
   return gptr() == egptr() ? traits_type::eof() : traits_type::to_int_type(*gptr());
 }
-
+#endif
 // }}}
 
 namespace file_util {
~~~

**Comment by ckorn** [comment]
Works, thanks.
