### ISSUE TITLE
Failing build after update to Ubuntu Bionic 18.04.1

### ISSUE THREAD

**Issue by devbridie** [jaagr/polybar#1427]
## Build Process
```
git clone --recursive https://github.com/jaagr/polybar.git
mkdir polybar/build
cd polybar/build
cmake ..
sudo make install
```

* Output of `git describe --tags`: [3.2.0-29-gfbc5a9f](https://github.com/jaagr/polybar/commit/fbc5a9fb7f27e24e238d3c906e04f96e0498568b) current, as of two days ago.

## Build Log
```
$ cmake ..
-- Trying to enable ccache
-- Couldn't locate ccache, disabling ccache...
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- No build type specified; using RelWithDebInfo
-- Using supported compiler GNU-7.3.0
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Checking for module 'cairo-fc'
--   Found cairo-fc, version 1.15.10
-- Checking for module 'alsa'
--   Found alsa, version 1.1.3
-- Checking for module 'libcurl'
--   Found libcurl, version 7.58.0
-- Checking for module 'libmpdclient'
--   Found libmpdclient, version 2.11
-- Found Libiw: /usr/lib/x86_64-linux-gnu/libiw.so  
-- Checking for module 'libpulse'
--   Found libpulse, version 11.1
-- Checking for module 'xcb-xkb'
--   Found xcb-xkb, version 1.13
-- Checking for module 'xcb-randr'
--   Found xcb-randr, version 1.13
-- Checking for module 'xcb-randr>=1.12'
--   Found xcb-randr, version 1.13
-- Checking for module 'xcb-xrm'
--   Found xcb-xrm, version 1.0
-- Checking for module 'xcb-cursor'
--   Found xcb-cursor, version 0.1.1
--  Build:
--    Type: RelWithDebInfo
--    CC: /usr/bin/cc  -O2 -g -DNDEBUG
--    CXX: /usr/bin/c++  -Wall -Wextra -Werror -Wno-noexcept-type -O2 -pedantic -pedantic-errors -O2 -g -DNDEBUG
--    LD: /usr/bin/ld  
--  Targets:
-- [X]   polybar-msg
-- [ ]   testsuite
--  Module support:
-- [X]   alsa (1.1.3)
-- [X]   curl (7.58.0)
-- [X]   i3
-- [X]   mpd (2.11)
-- [X]   network
-- [X]   pulseaudio (11.1)
-- [X]   xkeyboard (1.13)
--  X extensions:
-- [X]   xcb-randr (1.13)
-- [X]   xcb-randr (monitor support) (1.13)
-- [ ]   xcb-render
-- [ ]   xcb-damage
-- [ ]   xcb-sync
-- [ ]   xcb-composite
-- [X]   xcb-xkb (1.13)
-- [X]   xcb-xrm (1.0)
-- [X]   xcb-cursor (0.1.1)
--  Log options:
-- [X]   Trace logging
-- Font not found: fixed:pixelsize=10
-- Font not found: unifont:fontformat=truetype
-- Font not found: siji:pixelsize=10
-- Checking for module 'xcb-proto'
--   Found xcb-proto, version 1.13
-- Found PythonInterp: /usr/bin/python2.7 (found suitable version "2.7.15", minimum required is "2.7") 
-- XCB[XCB]: Found component XCB
-- Found XCB_XCB: /usr/lib/x86_64-linux-gnu/libxcb.so  
-- XCB[ICCCM]: Found component ICCCM
-- Found XCB_ICCCM: /usr/lib/x86_64-linux-gnu/libxcb-icccm.so  
-- XCB[EWMH]: Found component EWMH
-- Found XCB_EWMH: /usr/lib/x86_64-linux-gnu/libxcb-ewmh.so  
-- XCB[UTIL]: Found component UTIL
-- Found XCB_UTIL: /usr/lib/x86_64-linux-gnu/libxcb-util.so  
-- XCB[IMAGE]: Found component IMAGE
-- Found XCB_IMAGE: /usr/lib/x86_64-linux-gnu/libxcb-image.so  
-- Found XCB: /usr/lib/x86_64-linux-gnu/libxcb.so;/usr/lib/x86_64-linux-gnu/libxcb-icccm.so;/usr/lib/x86_64-linux-gnu/libxcb-ewmh.so;/usr/lib/x86_64-linux-gnu/libxcb-util.so;/usr/lib/x86_64-linux-gnu/libxcb-image.so  
-- Searching for xcbgen with python2
-- Found xcbgen in /usr/lib/python2.7/dist-packages
-- XCB[RANDR]: Found component RANDR
-- Found XCB_RANDR: /usr/lib/x86_64-linux-gnu/libxcb-randr.so  
-- Found XCB: /usr/lib/x86_64-linux-gnu/libxcb.so;/usr/lib/x86_64-linux-gnu/libxcb-icccm.so;/usr/lib/x86_64-linux-gnu/libxcb-ewmh.so;/usr/lib/x86_64-linux-gnu/libxcb-util.so;/usr/lib/x86_64-linux-gnu/libxcb-image.so;/usr/lib/x86_64-linux-gnu/libxcb-randr.so  
-- XCB[XKB]: Found component XKB
-- Found XCB_XKB: /usr/lib/x86_64-linux-gnu/libxcb-xkb.so  
-- Found XCB: /usr/lib/x86_64-linux-gnu/libxcb.so;/usr/lib/x86_64-linux-gnu/libxcb-icccm.so;/usr/lib/x86_64-linux-gnu/libxcb-ewmh.so;/usr/lib/x86_64-linux-gnu/libxcb-util.so;/usr/lib/x86_64-linux-gnu/libxcb-image.so;/usr/lib/x86_64-linux-gnu/libxcb-randr.so;/usr/lib/x86_64-linux-gnu/libxcb-xkb.so  
-- xpp: including xcb proto randr.xml
-- xpp: including xcb proto xkb.xml
-- xpp: including xcb proto xproto.xml
-- Checking for module 'jsoncpp>=1.7.7'
--   Requested 'jsoncpp >= 1.7.7' but version of jsoncpp is 1.7.4
You may find new versions of jsoncpp at https://github.com/open-source-parsers/jsoncpp
-- Could not find jsoncpp>=1.7.7 -- building static lib...
-- JsonCpp Version: 1.7.7
-- Found PythonInterp: /usr/bin/python2.7 (found suitable version "2.7.15", minimum required is "2.6") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dereck/Themes/polybar/build


$ make install
Scanning dependencies of target xpp
[  1%] Linking CXX static library libxpp.a
[  4%] Built target xpp
Scanning dependencies of target jsoncpp_lib_static
[  5%] Building CXX object lib/i3ipcpp/libs/jsoncpp-1.7.7/src/lib_json/CMakeFiles/jsoncpp_lib_static.dir/json_reader.cpp.o
[  6%] Building CXX object lib/i3ipcpp/libs/jsoncpp-1.7.7/src/lib_json/CMakeFiles/jsoncpp_lib_static.dir/json_value.cpp.o
[  7%] Building CXX object lib/i3ipcpp/libs/jsoncpp-1.7.7/src/lib_json/CMakeFiles/jsoncpp_lib_static.dir/json_writer.cpp.o
[  8%] Linking CXX static library libjsoncpp.a
[  8%] Built target jsoncpp_lib_static
Scanning dependencies of target i3ipc++
[  8%] Building CXX object lib/i3ipcpp/CMakeFiles/i3ipc++.dir/src/ipc.cpp.o
[  9%] Building CXX object lib/i3ipcpp/CMakeFiles/i3ipc++.dir/src/ipc-util.cpp.o
[ 10%] Linking CXX static library libi3ipc++.a
[ 10%] Built target i3ipc++
Scanning dependencies of target polybar-msg
[ 11%] Building CXX object bin/CMakeFiles/polybar-msg.dir/ipc.cpp.o
[ 12%] Building CXX object bin/CMakeFiles/polybar-msg.dir/utils/env.cpp.o
[ 13%] Building CXX object bin/CMakeFiles/polybar-msg.dir/utils/file.cpp.o
[ 14%] Building CXX object bin/CMakeFiles/polybar-msg.dir/utils/string.cpp.o
[ 15%] Linking CXX executable polybar-msg
[ 15%] Built target polybar-msg
Scanning dependencies of target polybar
[ 16%] Building CXX object bin/CMakeFiles/polybar.dir/adapters/alsa/control.cpp.o
[ 17%] Building CXX object bin/CMakeFiles/polybar.dir/adapters/alsa/mixer.cpp.o
[ 18%] Building CXX object bin/CMakeFiles/polybar.dir/adapters/mpd.cpp.o
[ 20%] Building CXX object bin/CMakeFiles/polybar.dir/adapters/net.cpp.o
[ 21%] Building CXX object bin/CMakeFiles/polybar.dir/adapters/net_iw.cpp.o
[ 22%] Building CXX object bin/CMakeFiles/polybar.dir/adapters/pulseaudio.cpp.o
[ 23%] Building CXX object bin/CMakeFiles/polybar.dir/cairo/utils.cpp.o
[ 24%] Building CXX object bin/CMakeFiles/polybar.dir/components/bar.cpp.o
[ 25%] Building CXX object bin/CMakeFiles/polybar.dir/components/builder.cpp.o
[ 26%] Building CXX object bin/CMakeFiles/polybar.dir/components/command_line.cpp.o
[ 27%] Building CXX object bin/CMakeFiles/polybar.dir/components/config.cpp.o
[ 28%] Building CXX object bin/CMakeFiles/polybar.dir/components/controller.cpp.o
[ 29%] Building CXX object bin/CMakeFiles/polybar.dir/components/ipc.cpp.o
[ 30%] Building CXX object bin/CMakeFiles/polybar.dir/components/logger.cpp.o
[ 31%] Building CXX object bin/CMakeFiles/polybar.dir/components/parser.cpp.o
[ 32%] Building CXX object bin/CMakeFiles/polybar.dir/components/renderer.cpp.o
[ 33%] Building CXX object bin/CMakeFiles/polybar.dir/components/screen.cpp.o
[ 34%] Building CXX object bin/CMakeFiles/polybar.dir/components/taskqueue.cpp.o
[ 35%] Building CXX object bin/CMakeFiles/polybar.dir/drawtypes/animation.cpp.o
[ 36%] Building CXX object bin/CMakeFiles/polybar.dir/drawtypes/iconset.cpp.o
[ 37%] Building CXX object bin/CMakeFiles/polybar.dir/drawtypes/label.cpp.o
[ 38%] Building CXX object bin/CMakeFiles/polybar.dir/drawtypes/progressbar.cpp.o
[ 40%] Building CXX object bin/CMakeFiles/polybar.dir/drawtypes/ramp.cpp.o
[ 41%] Building CXX object bin/CMakeFiles/polybar.dir/events/signal_emitter.cpp.o
[ 42%] Building CXX object bin/CMakeFiles/polybar.dir/events/signal_receiver.cpp.o
[ 43%] Building CXX object bin/CMakeFiles/polybar.dir/main.cpp.o
[ 44%] Building CXX object bin/CMakeFiles/polybar.dir/modules/alsa.cpp.o
[ 45%] Building CXX object bin/CMakeFiles/polybar.dir/modules/backlight.cpp.o
[ 46%] Building CXX object bin/CMakeFiles/polybar.dir/modules/battery.cpp.o
[ 47%] Building CXX object bin/CMakeFiles/polybar.dir/modules/bspwm.cpp.o
[ 48%] Building CXX object bin/CMakeFiles/polybar.dir/modules/counter.cpp.o
[ 49%] Building CXX object bin/CMakeFiles/polybar.dir/modules/cpu.cpp.o
[ 50%] Building CXX object bin/CMakeFiles/polybar.dir/modules/date.cpp.o
[ 51%] Building CXX object bin/CMakeFiles/polybar.dir/modules/fs.cpp.o
[ 52%] Building CXX object bin/CMakeFiles/polybar.dir/modules/github.cpp.o
[ 53%] Building CXX object bin/CMakeFiles/polybar.dir/modules/i3.cpp.o
[ 54%] Building CXX object bin/CMakeFiles/polybar.dir/modules/ipc.cpp.o
[ 55%] Building CXX object bin/CMakeFiles/polybar.dir/modules/memory.cpp.o
[ 56%] Building CXX object bin/CMakeFiles/polybar.dir/modules/menu.cpp.o
[ 57%] Building CXX object bin/CMakeFiles/polybar.dir/modules/meta/base.cpp.o
[ 58%] Building CXX object bin/CMakeFiles/polybar.dir/modules/mpd.cpp.o
[ 60%] Building CXX object bin/CMakeFiles/polybar.dir/modules/network.cpp.o
[ 61%] Building CXX object bin/CMakeFiles/polybar.dir/modules/pulseaudio.cpp.o
[ 62%] Building CXX object bin/CMakeFiles/polybar.dir/modules/script.cpp.o
[ 63%] Building CXX object bin/CMakeFiles/polybar.dir/modules/systray.cpp.o
[ 64%] Building CXX object bin/CMakeFiles/polybar.dir/modules/temperature.cpp.o
[ 65%] Building CXX object bin/CMakeFiles/polybar.dir/modules/text.cpp.o
[ 66%] Building CXX object bin/CMakeFiles/polybar.dir/modules/xbacklight.cpp.o
[ 67%] Building CXX object bin/CMakeFiles/polybar.dir/modules/xkeyboard.cpp.o
[ 68%] Building CXX object bin/CMakeFiles/polybar.dir/modules/xwindow.cpp.o
[ 69%] Building CXX object bin/CMakeFiles/polybar.dir/modules/xworkspaces.cpp.o
[ 70%] Building CXX object bin/CMakeFiles/polybar.dir/utils/bspwm.cpp.o
[ 71%] Building CXX object bin/CMakeFiles/polybar.dir/utils/command.cpp.o
[ 72%] Building CXX object bin/CMakeFiles/polybar.dir/utils/concurrency.cpp.o
[ 73%] Building CXX object bin/CMakeFiles/polybar.dir/utils/env.cpp.o
[ 74%] Building CXX object bin/CMakeFiles/polybar.dir/utils/factory.cpp.o
[ 75%] Building CXX object bin/CMakeFiles/polybar.dir/utils/file.cpp.o
[ 76%] Building CXX object bin/CMakeFiles/polybar.dir/utils/http.cpp.o
[ 77%] Building CXX object bin/CMakeFiles/polybar.dir/utils/i3.cpp.o
[ 78%] Building CXX object bin/CMakeFiles/polybar.dir/utils/inotify.cpp.o
[ 80%] Building CXX object bin/CMakeFiles/polybar.dir/utils/io.cpp.o
[ 81%] Building CXX object bin/CMakeFiles/polybar.dir/utils/process.cpp.o
[ 82%] Building CXX object bin/CMakeFiles/polybar.dir/utils/socket.cpp.o
[ 83%] Building CXX object bin/CMakeFiles/polybar.dir/utils/string.cpp.o
[ 84%] Building CXX object bin/CMakeFiles/polybar.dir/utils/throttle.cpp.o
[ 85%] Building CXX object bin/CMakeFiles/polybar.dir/x11/atoms.cpp.o
[ 86%] Building CXX object bin/CMakeFiles/polybar.dir/x11/connection.cpp.o
[ 87%] Building CXX object bin/CMakeFiles/polybar.dir/x11/cursor.cpp.o
[ 88%] Building CXX object bin/CMakeFiles/polybar.dir/x11/ewmh.cpp.o
[ 89%] Building CXX object bin/CMakeFiles/polybar.dir/x11/extensions/randr.cpp.o
/home/dereck/Themes/polybar/src/x11/extensions/randr.cpp:90:30: error: no member named 'get_monitors' in
      'polybar::v3_2_0_29_gfbc5a9f::connection'
      for (auto&& mon : conn.get_monitors(root, true).monitors()) {
                        ~~~~ ^
1 error generated.
bin/CMakeFiles/polybar.dir/build.make:1718: recipe for target 'bin/CMakeFiles/polybar.dir/x11/extensions/randr.cpp.o' failed
make[2]: *** [bin/CMakeFiles/polybar.dir/x11/extensions/randr.cpp.o] Error 1
CMakeFiles/Makefile2:853: recipe for target 'bin/CMakeFiles/polybar.dir/all' failed
make[1]: *** [bin/CMakeFiles/polybar.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

```

## Environment:
* Distro (with Version): Ubuntu Bionic 18.04.1

## Additional context
1. This happened after an upgrade to 18.04, when I received `CURL_OPENSSL_3` not found, as per #1192. My next step was to compile against latest.
2. I received this error message. Another related issue (#644) was found, and [this comment suggests a version mismatch amongst xcb packages.](https://github.com/jaagr/polybar/issues/644#issuecomment-314916405) However, my versions all match, that is, 1.13. Using these steps to downgrade to 1.11 did not solve my issue. I started from scratch and still had the same issue.
3. I have reverted back to the `apt` provided packages, where all versions are matched. This is shown by the following: `$ pkg-config --print-provides xcb-randr` `xcb-randr = 1.13` `$ pkg-config --print-provides xcb-proto` `xcb-proto = 1.13`

["So we'll have to make the versions match either by upgrading all the libxcb-* packages to 1.12-1"](https://github.com/jaagr/polybar/issues/644#issuecomment-314916405) Here, I demonstrate that these packages are most recent and matching.
```
$ dpkg -l | grep 'ii' | grep libxcb
ii  libxcb-composite0:amd64                       1.13-1                                  amd64        X C Binding, composite extension
ii  libxcb-composite0-dev:amd64                   1.13-1                                  amd64        X C Binding, composite extension, development files
ii  libxcb-cursor-dev:amd64                       0.1.1-4ubuntu1                          amd64        utility libraries for X C Binding -- cursor, development files
ii  libxcb-cursor0:amd64                          0.1.1-4ubuntu1                          amd64        utility libraries for X C Binding -- cursor
ii  libxcb-dpms0:amd64                            1.13-1                                  amd64        X C Binding, dpms extension
ii  libxcb-dpms0-dev:amd64                        1.13-1                                  amd64        X C Binding, dpms extension, development files
ii  libxcb-dri2-0:amd64                           1.13-1                                  amd64        X C Binding, dri2 extension
ii  libxcb-dri2-0:i386                            1.13-1                                  i386         X C Binding, dri2 extension
ii  libxcb-dri3-0:amd64                           1.13-1                                  amd64        X C Binding, dri3 extension
ii  libxcb-dri3-0:i386                            1.13-1                                  i386         X C Binding, dri3 extension
ii  libxcb-ewmh-dev:amd64                         0.4.1-1ubuntu1                          amd64        utility libraries for X C Binding -- ewmh, development files
ii  libxcb-ewmh2:amd64                            0.4.1-1ubuntu1                          amd64        utility libraries for X C Binding -- ewmh
ii  libxcb-glx0:amd64                             1.13-1                                  amd64        X C Binding, glx extension
ii  libxcb-glx0:i386                              1.13-1                                  i386         X C Binding, glx extension
ii  libxcb-icccm4:amd64                           0.4.1-1ubuntu1                          amd64        utility libraries for X C Binding -- icccm
ii  libxcb-icccm4-dev:amd64                       0.4.1-1ubuntu1                          amd64        utility libraries for X C Binding -- icccm, development files
ii  libxcb-image0:amd64                           0.4.0-1build1                           amd64        utility libraries for X C Binding -- image
ii  libxcb-image0-dev:amd64                       0.4.0-1build1                           amd64        utility libraries for X C Binding -- image, development files
ii  libxcb-keysyms1:amd64                         0.4.0-1                                 amd64        utility libraries for X C Binding -- keysyms
ii  libxcb-keysyms1-dev:amd64                     0.4.0-1                                 amd64        utility libraries for X C Binding -- keysyms, development files
ii  libxcb-present0:amd64                         1.13-1                                  amd64        X C Binding, present extension
ii  libxcb-present0:i386                          1.13-1                                  i386         X C Binding, present extension
ii  libxcb-randr0:amd64                           1.13-1                                  amd64        X C Binding, randr extension
ii  libxcb-randr0-dev:amd64                       1.13-1                                  amd64        X C Binding, randr extension, development files
ii  libxcb-render-util0:amd64                     0.3.9-1                                 amd64        utility libraries for X C Binding -- render-util
ii  libxcb-render-util0-dev:amd64                 0.3.9-1                                 amd64        utility libraries for X C Binding -- render-util
ii  libxcb-render0:amd64                          1.13-1                                  amd64        X C Binding, render extension
ii  libxcb-render0:i386                           1.13-1                                  i386         X C Binding, render extension
ii  libxcb-render0-dev:amd64                      1.13-1                                  amd64        X C Binding, render extension, development files
ii  libxcb-res0:amd64                             1.13-1                                  amd64        X C Binding, res extension
ii  libxcb-shape0:amd64                           1.13-1                                  amd64        X C Binding, shape extension
ii  libxcb-shape0-dev:amd64                       1.13-1                                  amd64        X C Binding, shape extension, development files
ii  libxcb-shm0:amd64                             1.13-1                                  amd64        X C Binding, shm extension
ii  libxcb-shm0:i386                              1.13-1                                  i386         X C Binding, shm extension
ii  libxcb-shm0-dev:amd64                         1.13-1                                  amd64        X C Binding, shm extension, development files
ii  libxcb-sync1:amd64                            1.13-1                                  amd64        X C Binding, sync extension
ii  libxcb-sync1:i386                             1.13-1                                  i386         X C Binding, sync extension
ii  libxcb-util-dev:amd64                         0.4.0-0ubuntu3                          amd64        utility libraries for X C Binding -- atom, aux and event
ii  libxcb-util0-dev:amd64                        0.4.0-0ubuntu3                          amd64        dummy transitional package for utility libraries for X C Binding -- atom, aux and event
ii  libxcb-util1:amd64                            0.4.0-0ubuntu3                          amd64        utility libraries for X C Binding -- atom, aux and event
ii  libxcb-xfixes0:amd64                          1.13-1                                  amd64        X C Binding, xfixes extension
ii  libxcb-xfixes0:i386                           1.13-1                                  i386         X C Binding, xfixes extension
ii  libxcb-xfixes0-dev:amd64                      1.13-1                                  amd64        X C Binding, xfixes extension, development files
ii  libxcb-xinerama0:amd64                        1.13-1                                  amd64        X C Binding, xinerama extension
ii  libxcb-xinerama0-dev:amd64                    1.13-1                                  amd64        X C Binding, xinerama extension, development files
ii  libxcb-xkb-dev:amd64                          1.13-1                                  amd64        X C Binding, XKEYBOARD extension, development files
ii  libxcb-xkb1:amd64                             1.13-1                                  amd64        X C Binding, XKEYBOARD extension
ii  libxcb-xrm-dev:amd64                          1.0-3                                   amd64        utility functions for the X resource manager, development files
ii  libxcb-xrm0:amd64                             1.0-3                                   amd64        utility functions for the X resource manager
ii  libxcb-xv0:amd64                              1.13-1                                  amd64        X C Binding, xv extension
ii  libxcb1:amd64                                 1.13-1                                  amd64        X C Binding
ii  libxcb1:i386                                  1.13-1                                  i386         X C Binding
ii  libxcb1-dev:amd64                             1.13-1                                  amd64        X C Binding, development files
```

Any help is appreciated. My desktop just isn't the same without this amazing project.

**Comment by devbridie** [comment]
After reading more issues, I have come across #1206's [workaround](https://github.com/jaagr/polybar/issues/1206#issuecomment-386067590).

I used this to build the project successfully:
```
$ git clone --recursive https://github.com/jaagr/polybar
$ cd polybar/lib/xpp
$ git checkout master
$ rm include/xpp/proto/*
$ cd
$ mkdir polybar/build
$ cd polybar/build
$ cmake ..
$ sudo make install
```

However, now I am unable to reproduce my old problem after an uninstall.

**Comment by patrick96** [comment]
I was just about to suggest that.

I think you didn't do a fresh git clone. I suspect that the `lib/xpp/include/xpp/proto/*` files were generated before you upgraded ubuntu and were never regenerated which caused this probably because with the new ubuntu version there is some new feature enabled which wasn't before but the generated xpp files don't reflect that.

If you build with a fresh git clone you should never run into this issue.

**Comment by devbridie** [comment]
I think this could be correct. In my original working directory, I had used `git submodule update --recursive`. Even though I was clearing my build folder, the contents of `lib/xpp/include/xpp/proto/*` will not be removed with this. Perhaps a build step should be added that will remove files (or other related files) in `lib/xpp/include/xpp/proto/*` to prevent such an issue in the future?

**Comment by patrick96** [comment]
Yeah we probably should add that. @skystrife I think you last worked on that part of xpp and you also have more cmake experience than me, what would it take to regenerate all the header files before each compilation?
